class UserAlreadyExists(Exception):
    pass


class AuthenticationError(Exception):
    pass


class NotAuthenticatedError(Exception):
    pass
